import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../src/shared/styles/custom-shape-divider.css';
import '../src/shared/styles/globals.css';
import Header from '@/src/shared/components/layouts/header';
import Footer from '@/src/shared/components/layouts/footer';
import PageDivTop from '@/src/shared/components/pageDivTop';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Header />
                <PageDivTop />
                <main className='min-h-[70vh]'>{children}</main>

                {children}
                <Footer />
            </body>
        </html>
    );
}
